---
- name: Firefox | Create temp structure
  ansible.windows.win_file:
    path: "C:/temp"
    state: directory

- name: Firefox | Download Firefox
  win_get_url:
    url: "https://download.mozilla.org/?product=firefox-msi-latest-ssl&os=win64&lang=pt-BR"
    dest: "C:/temp/firefox.msi"
    validate_certs: false

- name: Firefox | Installing Firefox
  ansible.windows.win_package:
    path: C:\temp\firefox.msi
    arguments: 
      - 'TASKBAR_SHORTCUT=true'
      - 'DESKTOP_SHORTCUT=true'
      - 'INSTALL_MAINTENANCE_SERVICE=false'
    state: present

