---
- hosts: all
  gather_facts: false
  vars:
    ansible_python_interpreter: "/usr/bin/python3"
    target_addr: '{{ hostvars[inventory_hostname]["inventory_hostname"] }}'
  
  tasks:
  - name: Add target to Ansible Hosts
    add_host:
      name: '{{ target_addr }}'
      ansible_connection: winrm
      ansible_winrm_transport: ntlm
      ansible_winrm_server_cert_validation: ignore
      ansible_winrm_port: 5986
      group: "target"

- hosts: "target"
  gather_facts: true
  vars_files:
    - vars.yml
  vars:
    ansible_python_interpreter: "/usr/bin/python3"
  
  tasks:
  - name: Wait for system to become reachable over ip
    wait_for_connection:
      timeout: 900

  - name: Enable Remote Desktop
    win_shell: |
      New-ItemProperty -Path "HKLM:\System\CurrentControlSet\Control\terminal server" -Name fDenyTSConnections -Value 0 -ErrorAction SilentlyContinue | Out-Null
      Set-ItemProperty -Path "HKLM:\System\CurrentControlSet\Control\terminal server" -Name fDenyTSConnections -Value 0
      Set-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp" -Name "UserAuthentication" -Value 1
      Enable-NetFirewallRule -DisplayGroup "Remote Desktop"


